name = "Subtrate's Node Template"
description = "A tool to customize the template to get started with building blockchains with Substrate."
kickstart_version = 1
ignore = [
    "*",
    "substrate-node-template/.github/workflows/build-push-template",
    "substrate-node-template/docker-compose.yml",
    "README.md"
]

[[variables]]
name = "node_name"
default = "template"
prompt = "What are you calling your node?"

[[variables]]
name = "pallet_name"
default = "template"
prompt = "What are you calling your pallet?"